'''
Extract the last frame from a multi-frame XYZ file
Author: Dirac4pi
env:base
'''

#-------------------------------------------------------------------------------
def isint(string:str) -> bool:
  '''
  Determine whether the string is an integer or not
  --
  :string: input string\n
  return: true/false
  '''
  try:
    int(string)
  except ValueError:
    return False
  else:
    return True

#-------------------------------------------------------------------------------
def celldump(jobname:str) -> str:
  '''
  Extract the cell information from CP2K output file
  --
  :jobname: CP2K job name\n
  return: cell information
  '''
  cellinfo = ' No cell info'
  try:
    open(jobname+'.inp', 'r', encoding='utf-8')
  except FileNotFoundError:
    print(f'Cannot find {jobname}.inp file, cell info will not be added.')
    return cellinfo
  with open(jobname+'.inp', 'r', encoding='utf-8') as f:
    lines = f.readlines()
    a = None
    b = None
    c = None
    for i, line in enumerate(lines):
      if line.strip().startswith('&CELL'):
        j = i + 1
        while not lines[j].strip().startswith('&END CELL'):
          if lines[j].strip().startswith('A'):
            a = lines[j].split()[1:4]
          elif lines[j].strip().startswith('B'):
            b = lines[j].split()[1:4]
          elif lines[j].strip().startswith('C'):
            c = lines[j].split()[1:4]
          j += 1
        break
  if c is not None:
    cellinfo = f'Lattice=\"{a[0]} {a[1]} {a[2]} '+ \
                         f'{b[0]} {b[1]} {b[2]} '+ \
                         f'{c[0]} {c[1]} {c[2]}\"'+\
                         f'Properties=species:S:1:pos:R:3\n'
  elif b is not None:
    cellinfo = f'Lattice=\"{a[0]} {a[1]} {a[2]} '+ \
                         f'{b[0]} {b[1]} {b[2]}\"'+\
                         f'Properties=species:S:1:pos:R:3\n'
  else:
    cellinfo = f'Lattice=\"{a[0]} {a[1]} {a[2]}\"'+ \
                          f'Properties=species:S:1:pos:R:3\n'
  return cellinfo

#-------------------------------------------------------------------------------
def xyzdump(input_xyz: str, output_xyz: str) -> None:
  '''
  Extract the last frame from a multi-frame XYZ file
  --
  :input_xyz: title of input .xyz file\n
  :output_xyz: title of output .xyz file\n
  return: None
  '''
  with open(input_xyz, "r") as f:
    lines = f.readlines()
  i = len(lines)-1
  frame_end = 0
  while i > 0:
    if lines[i].strip() == "":
      i -= 1
      continue
    elif frame_end == 0:
      frame_end = i
    if isint(lines[i].strip()):
      frame_start = i
      break
    i -= 1
  last_frame = lines[frame_start:frame_end+1]
  if last_frame is None:
    raise RuntimeError("Invalid XYZ frame.")
  # modify the title content if input_xyz is generated by CP2K
  if input_xyz.endswith('-pos-1.xyz'):
    print('input .xyz file is generated by CP2K, cell info will be added.')
    cellinfo = celldump(input_xyz.removesuffix('-pos-1.xyz'))
    last_frame[1] = cellinfo
  with open(output_xyz, "w") as f:
    f.writelines(last_frame)

#===============================================================================
if __name__ == "__main__":
  import sys
  if len(sys.argv) != 3:
    print("Usage: xyzdump input.[xyz|trj|tre|trej]")
    sys.exit(1)
  input_file = sys.argv[1]
  output_file = sys.argv[2]
  if input_file.endswith('.xyz'):
    xyzdump(input_file,output_file)
  elif input_file.endswith('.trj'):
    xyzdump(input_file,output_file)
  elif input_file.endswith('.tre'):
    xyzdump(input_file,output_file)
  elif input_file.endswith('.trej'):
    xyzdump(input_file,output_file)
  else:
    print("unrecognize input file type")
    sys.exit(1)
